vim.keymap.set("n", "<Esc>", "<cmd>nohlsearch<CR>", { desc = "No hlsearch" })
vim.keymap.set("n", "<C-d>", "<C-d>zz", { desc = "Scroll down and center" })
vim.keymap.set("n", "<C-u>", "<C-u>zz", { desc = "Scroll up and center" })
vim.keymap.set("n", "n", "nzzzv", { desc = "Next search result and center" })
vim.keymap.set("n", "N", "Nzzzv", { desc = "Previous search result and center" })
vim.keymap.set({ "n", "v" }, "<leader>d", [["_d]], { desc = "Delete without yanking" })
vim.keymap.set("x", "<leader>p", [["_dP]], { desc = "Paste without yanking in visual mode" })
vim.keymap.set({ "n", "v" }, "<leader>y", [["+y]], { desc = "Yank to system clipboard (normal and visual)" })
vim.keymap.set("n", "<leader>Y", [["+Y]], { desc = "Yank line to system clipboard" })
vim.keymap.set("n", "Q", "@q", { desc = "Replay macro in register q" })
vim.keymap.set("n", "<leader>fb", vim.lsp.buf.format, { desc = "Format buffer" })
vim.keymap.set("n", "<leader>q", vim.cmd.q, { desc = ":[Q]uit" })
vim.keymap.set("t", "<Esc>", '<C-\\><C-N>', { desc = ":Exit terminal mode" })
vim.keymap.set('n', '<Right>', ':tabnext<CR>', { noremap = true, silent = true, desc = "Next tab" })
vim.keymap.set('n', '<left>', ':tabprevious<CR>', { noremap = true, silent = true, desc = "Prev tab" })
vim.keymap.set('n', '<leader>tn', ':tab split<CR>', { noremap = true, silent = true, desc = "tab split" })

